name=Activity Board Library
version=1.0.0
author=Sigi Jeske <sigi@tecsi.de>
maintainer=Sigi Jeske <sigi@tecsi.de>
sentence=Base Library for Activity Board.
paragraph=Supports: Activity Boards.
category=Activity Board
url=https://github.com/jeskes/activityboard.git
architectures=*